- id: check-docusaurus-frontmatter
  name: Check Docusaurus frontmatter
  description: Ensure that the minimum frontmatter settings are present
  language: python
  entry: check-docusaurus-frontmatter
  types: [markdown]